### ISSUE TITLE
Series Colours Not Showing For Line Chart

### ISSUE THREAD

**Issue by OlenaPleshan** [jtblin/angular-chart.js#114]
![screen shot 2015-05-24 at 00 08 02](https://cloud.githubusercontent.com/assets/5902215/7785895/7c6ca3b4-01a9-11e5-9065-3a7936aba7a3.jpg)

I only modified data from the example, did not touch any configuration. However, maybe I did touch something by mistake :-)

Markup is exactly (or seems to be exactly) like in the example page

      <canvas id="line" class="chart chart-line ng-isolate-scope" data="data" labels="labels" legend="true" click="onClick" hover="onHover" series="series" height="140" width="400" style="width: 400px; height: 140px;"></canvas>

However, list styling for chart-legend does not get reset. 

Do you have an idea what is missing from markup to get the list elements styled correctly?

Thanks a mil!

**Comment by rhwood** [comment]
I think that if you want to change the colors, you need to add a ````colours="colours"```` attribute to your canvas element.

**Comment by jtblin** [comment]
As @rhwood said.

**Comment by OlenaPleshan** [comment]
The question is not about changing colours. The question is that the legend (series) does not give an idea about which line shows which stats. 

![screen shot 2015-05-29 at 12 16 26](https://cloud.githubusercontent.com/assets/5902215/7880739/b9513f72-05fc-11e5-9616-dd20f34d46da.jpg)

**Comment by jtblin** [comment]
Works for me, could you provide a repro case e.g. http://jsbin.com/dufibi/3/edit?html,js,output?

![image](https://cloud.githubusercontent.com/assets/1388974/7880830/a0ae23b0-0640-11e5-8fee-0ca0d87cd5e9.png)

**Comment by OlenaPleshan** [comment]
solved by including <link rel="stylesheet" href="http://cdn.rawgit.com/jtblin/angular-chart.js/master/dist/angular-chart.css" type="text/css" />

could you please add this to the instructions on the front page :-) for folks like me... :-D thanks guys!

**Comment by jtblin** [comment]
Your sentence is incomplete, not sure what's missing in the doc ;)

**Comment by mapugina** [comment]
I had the same issue with the same snippet and it seemed to be caused because I hadn't included the css file in my index.html. I can't say for sure but that might be what @OlenaPleshan meant.

**Comment by neoram88** [comment]
@OlenaPleshan I'm having the same problem. Could you please tell me how you fixed it?

**Comment by jtblin** [comment]
It could be the `css`. @neoram88 have you included it?

**Comment by neoram88** [comment]
@jtblin yup I , the 'angular-chart.css' is what you mean right?
and if I inspect the element I see this:
 `<chart-legend><ul class="line-legend"><li><span style="background-color:rgba(151,187,205,1)"></span>2014</li><li><span style="background-color:rgba(220,220,220,1)"></span>2015</li></ul></chart-legend>"`

But only the text '2014' is visible in the page.

**Comment by vorktanamobay** [comment]
This is missing from the current css file

`.line-legend >li > span{
  display: block;
  position: absolute;
  left: 0;
  top: 0;
  width: 20px;
  height: 20px;
  border-radius: 5px;
}
`

**Comment by jtblin** [comment]
Which version of angular-chart.js and chart.js are you using?

**Comment by yisca12345** [comment]
thank you!   @vorktanamobay you save my life.

**Comment by ghiscoding** [comment]
I also could not see the legend and then I saw you guys mentioned the `angular-chart.css`. Well it looks like this CSS does not exist anywhere in the current version. 

Luckily I found the `angular-chart.css` inside a [Plunker demo](http://plnkr.co/edit/386pA8?p=preview) that is referenced in this other [issue 412 - legend not displayed for radar Angular-chart.js](https://github.com/jtblin/angular-chart.js/issues/412). It's actually a good thing that I felt on that other issue since another undocumented feature is missing as well. I needed to use the `chart-options` and `display: true` to finally get the legends working. 

At the end, what is missing in the current project
* `angular-chart.css` => found it in this [Plunker demo](http://plnkr.co/edit/386pA8?p=preview)
* `$scope.options = { legend: { display: true } };` => undocumented, the Bar Chart legends are shown on the main page the `javascript` doesn't reflect it.

**Comment by jtblin** [comment]
The css is for a previous version of the lib, it isn't required anymore in
1.x. see the notes in the readme...

The legend is a standard Chart.js option now hence why it is not
specifically documented, however you can see examples on the demo site or
in examples/app.js.

On 26 Jul 2016 6:38 AM, "Ghislain B." <notifications@github.com> wrote:

I also could not see the legend and then I saw you guys mentioned the
angular-chart.css. Well it looks like this CSS does not exist anywhere in
the current version.

Luckily I found the angular-chart.css inside a Plunker demo
<http://plnkr.co/edit/386pA8?p=preview> that is referenced in this other issue
412 - legend not displayed for radar Angular-chart.js
<https://github.com/jtblin/angular-chart.js/issues/412>. It's actually a
good thing that I felt on that other issue since another undocumented
feature is missing as well. I needed to use the chart-options and display:
true to finally get the legends working.

At the end, what is missing in the current project

   - angular-chart.css => found it in this Plunker demo
   <http://plnkr.co/edit/386pA8?p=preview>
   - $scope.options = { legend: { display: true } }; => undocumented, the
   Bar Chart legends are shown on the main page the javascript doesn't
   reflect it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jtblin/angular-chart.js/issues/114#issuecomment-235077322>,
or mute the thread

**Comment by ghiscoding** [comment]
Ah yes you are right, it still works after removing CSS, thanks for the fast reply. 

Except that on the main page, scrolling to the "Bar Chart", it does display the "Legends", however the `markup` and `javascript` sections (shown on the left) aren't mentioning the `chart-options`. It would help to get them updated.

The markup section is missing the `chart-options="options"`, so it should be:
```html
<canvas id="bar" class="chart chart-bar"
  chart-options="options" chart-data="data" chart-labels="labels" chart-series="series"
</canvas>
```

The javascript section should be:
```javascript
angular.module("app", ["chart.js"]).controller("BarCtrl", function ($scope) {
  $scope.labels = ['2006', '2007', '2008', '2009', '2010', '2011', '2012'];
  $scope.series = ['Series A', 'Series B'];
  $scope.options = { legend: { display: true } }; // --> this is missing 

  $scope.data = [
    [65, 59, 80, 81, 56, 55, 40],
    [28, 48, 40, 19, 86, 27, 90]
  ];
});
```

Thanks for the great package, it's super easy to setup :)

**Comment by jtblin** [comment]
Thanks for pointing out, PR welcome ;) (the file to modify if someone
actually wants to fix that is examples/charts.template.html).

**Comment by ghiscoding** [comment]
Here's the PR if you want to merge it.

**Comment by edohkodjo** [comment]
Hi! I have the same issue with the legend option. Maybe that there is something i did wrong. This is the [jsbin template](http://jsbin.com/vezukakuqe/edit?html,js,output)

**Comment by edohkodjo** [comment]
In the legend, instead of having the name of series, i have "undefined"

**Comment by jtblin** [comment]
@edohkodjo , it's `chart-series` not `series`.
