### ISSUE TITLE
Maybe consider not to redraw the whole chart just because one data was added/removed

### ISSUE THREAD

**Issue by zmLGBBM** [jtblin/angular-chart.js#115]
First of all, good job man! I was seeking all afternoon for data binding with chart.js, and here it is.

Second, maybe consider just update the chart when data was modified, or just add one (or several) point(s) each time the data was extended, instead of redraw the whole thing. The functions for that is here (=> http://www.chartjs.org/docs/#line-chart-prototype-methods).

Just for instance, maybe make updateChart like this: 

    function updateChart(chart, values, scope) {
      var dat = [];
      var pos = scope.data[0].length - 1;
      scope.data.forEach(function (d) {
        dat.push(d[pos]);
      });
      
      var l = scope.labels[scope.labels.length - 1];
      
      chart.addData(dat, l);
      scope.$emit('update', chart);
    }

This'll add one point each time when the scope.data was extended, also you might wanna comment the label watching thing...

    //scope.$watch('labels', resetChart, true);

It works fine for me, with great animation, you might wanna try it out. ;)

**Comment by jtblin** [comment]
Thanks for the suggestion. Adding/removing isn't that simple, there is really no telling if the data was added at the end or if another value was inserted at the beginning or in the middle for example. The correct way would probably be to add the correct number of elements to the array, and then to update all the values. Moreover the arrays are structured differently for the different types of charts so it'd need to handle all cases. Anyhow, adding or removing items would also change the scale which would looks a bit weird maybe, I'd suggest you keep the same number of items in the array if possible e.g. remove the first element and add one element at the end as it will update the charts instead of destroying and re-creating it. This is more or less how the realtime chart is done on the demo page: http://jtblin.github.io/angular-chart.js/

Re: labels, it may work in case you change both data and labels but if you only change the labels then the chart wouldn't be updated.

**Comment by zmLGBBM** [comment]
Thanks for the advice. 

There's a 

    .update( )

method added along with the **addData()**. I'm thinking maybe to dynamically monitor the changes and choose which method to call, like if there's a point was append to the data source, call the **addData()**, but if there's a point's value was changed, call the **update()** method. If it's not that easy to accomplish, maybe consider let the user tell which point was modified.

As for the `add point in the middle of the sequence` thing... I don't think it's that often to happen. But if so, maybe consider:
1. Chop the last one of the sequence, save it.
2. Call **update()** to make the chart animate to the right position.
3. Append the chopped one to the last, and call **addData()** to make sure all the data was presented correctly.

Would like to hear from you soon. ;-)

**Comment by jtblin** [comment]
> As for the add point in the middle of the sequence thing... I don't think it's that often to happen

It doesn't matter that it may not happen often, the reality is that it could be an entirely new chart with completely new data, you have absolutely no evidence that just one row was added or removed. 

>  I'm thinking maybe to dynamically monitor the changes and choose which method to call

Yeah, that's basically what I was saying above: 

* the number of elements added or removed for the 2 types of series (dataset i.e. [ [ ], [ ], ... ] or data [ , , , ... ]) need to be computed
* the appropriate `addData` or `removeData` need to be called (probably with `null` values)
* all the values in the array should be updated using `updateChart`

I'd accept a PR more or less doing this if you're keen.

That said, as I said before I don't think you should be adding elements, you'd probably want to keep the same number of elements in the array(s) to preserve the scale and give a realtime update movement but maybe I just don't understand your use case.

**Comment by zmLGBBM** [comment]
Haha, nah,, maybe I didn't think through.

Thanks anyways.

Ps. Was there at Sydney last summer (well, winter there). Looooooooved it there!

**Comment by dirttech** [comment]
@Z-Clive Maybe what you can do is use - 
`$interval(function () {
		if($scope.options.animation != false){
			console.log("stopping animation");
			$scope.options.animation = false;			
		}...`
before start updating a chart. So you animation will be close after initial rendering and no one will notice if the whole chart is being redrawn.
