### ISSUE TITLE
Module chart.js not found

### ISSUE THREAD

**Issue by carlosaviles** [jtblin/angular-chart.js#122]
Hi,

just installed the bower modules using 
    "chartjs": "1.0.1",
    "angular-chart": "*"
in bower.json. The modules get loaded.

I also have 
<script src="bower_components/chartjs/Chart.min.js"></script>
and
<script src="bower_components/angular-chart/angular-chart.js"></script>
but when I try to declare the module dependency inside Angular's app like this
angular.module('myApp', ['chart.js'])
I get an error because the dependency can't be resolved:
[$injector:modulerr] Failed to instantiate module chart.js due to:
[$injector:nomod] Module 'chart.js' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

What am I doing wrong? 

I am using angular 1.3.15.

Thanks!
Carlos.

**Comment by CiscoKidxx** [comment]
You have to make sure the chart.js is being a loaded first. View source and confirm it shows that it is loaded before angular-chart.ks.

**Comment by carlosaviles** [comment]
Hi,
thanks for answering.
I checked the source of the page and chart.js is loaded before angular-chart.js. Here's the source:


      <script src="bower_components/jquery/dist/jquery.js"></script>
      <script src="bower_components/chartjs/Chart.min.js"></script>
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/angular-resource/angular-resource.js"></script>
      <script src="bower_components/angular-cookies/angular-cookies.js"></script>
      <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
      <script src="bower_components/angular-route/angular-route.js"></script>
      <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
      <script src="bower_components/lodash/dist/lodash.compat.js"></script>
      <script src="bower_components/angular-socket-io/socket.js"></script>
      <script src="bower_components/d3/d3.js"></script>
      <script src="bower_components/c3/c3.js"></script>
      <script src="bower_components/angular-chart/angular-chart.js"></script>
      

Is there anything else I should check?

Best,
Carlos.

**Comment by shaohaolin** [comment]
I am using angular 1.3.15 as well. It works for me.
Try to clean the cache of your browser. And make sure angular-chart.js is loaded before your main javascript, usually load it before app.js.

**Comment by calvinKG** [comment]
Hi, 

I am experiencing the very same problem. 
Uncaught Error: [$injector:modulerr] Failed to instantiate module corporateDiaryApp due to:
Error: [$injector:modulerr] Failed to instantiate module chart.js due to:
Error: [$injector:nomod] Module 'chart.js' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.


index.html 
<script src="lib/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="lib/angular/angular.js"></script>

<script src="lib/angular-chart.js/dist/angular-chart.js"></script>


<script src="app.js"></script>
<script src="service/service.js"></script>

**Comment by brooka** [comment]
calvinKG - check your bower.json  file, maybe you loaded angular-chart rather than angular-chart.js

**Comment by fabrikate** [comment]
I am having the same trouble, I am loading Chart.js from bower before angular-chart. Angular-chart is before by app.js files. Also, when I checked the sources in the browser Chart is loading before angular-chart. Any idea why I am running into this bug?

**Comment by Chrono73** [comment]
Same here. My html page loads angular first, then Chart.js, then angular-chart.js, then my controller where I get the error.

**Comment by jtblin** [comment]
Post a jsbin or plunker repro.

**Comment by zoufri** [comment]
with angularjs 1.5.x use "`angular.module("Charts",["chart.js"])`..." not "`angular.module('Charts',['chart.js'])`..."
and be sure that `Chart.js `is before `angular-chart.js` in your html code  ;)

**Comment by fabrikate** [comment]
Thanks for the response! so I changed the injection of chart.js to double quotes, and confirmed that the chart.js is before the angular-chart.js on my html.

Attached is a jsbin of my code. The HTML page is big, but I included it all since I could be missing something something about conflicting libraries.

Thanks!

http://jsbin.com/rutuzo/edit?html,js

**Comment by jtblin** [comment]
Double quotes vs single quotes are not going to make any difference, both are valid JS options (I use single quotes everywhere). In your jsbin, angular is not even loading properly so it cannot work.

> auth0-angular-4.js:9 Uncaught ReferenceError: angular is not defined

Then if I add it before the other scripts I got error that `define` is not a function:

```
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.min.js"
  type="text/javascript">
</script>
```

> yupiniq.js:3 Uncaught TypeError: define is not a function

and an Angular injection error because module app is unknown which is basic angular error. I'd suggest you head to stackoverflow for this type of question.

> VM379 angular.min.js:6 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.9/$injector/modulerr?p0=app&p1=Error%3A%20%…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.9%2Fangular.min.js%3A17%3A350)

**Comment by fabrikate** [comment]
Hi  @jtblin, thanks for your response. Angular does load properly on my website, so my apologies that it wasn't able to function on the jsbin. I have searched stackoverflow and asked the question. My bug still persists! (http://stackoverflow.com/questions/37822184/angular-chart-chart-js-injector-error?noredirect=1#comment63265655_37822184)

 Is there any other insight as to why I am getting this error?

**Comment by jtblin** [comment]
Why don't you start from an example that works instead and just add your stuff? http://jsbin.com/cucoqe/1/edit?html,js,output

**Comment by fabrikate** [comment]
That was good advice! I incorporated the CDNs that you used in the jsbin instead of the bower_components and VOILA! No $inject errors and beautiful charts.  Thank you for your help!

**Comment by zoufri** [comment]
@fabrikate   good  , if you have other problems with chart ($http.get method , or any things) u are welcome ;)

**Comment by sAgime** [comment]
Hi

I'm having this error as well. Like you suggested, I tried to run your example ( http://jsbin.com/cucoqe/1/edit?html,js,output ) and start from there.
However, it does not seem to work (anymore?).

The console prints this out:
angular-chart.js:30 Uncaught TypeError: Cannot set property 'mode' of undefined

runner-3.39.11.min.js:1 error Script error. (line 0)

angular.js:4117Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.9/$injector/modulerr?p0=jsbin&p1=Error%3A%2…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.9%2Fangular.min.js%3A17%3A350)

**Comment by mustafacandan** [comment]
The path was changed. Instead use this: `<script src="/bower_components/chart.js/dist/Chart.min.js"></script>`
