### ISSUE TITLE
Should the $scope events emitted by angular-chart.js be namespaced ?

### ISSUE THREAD

**Issue by elnygren** [jtblin/angular-chart.js#222]
The docs say that angular-chart emits `create` and `update` events. I'm wondering, shouldn't they be namespaced in a better way such as `angular-chart:create` ? 

```
$scope.$on('create', function (event, chart) {
  console.log(chart);
});
```

I'm not an Angular pro but the current events seem a bit general to me? How does angular handle collisions in event names ?

**Comment by elnygren** [comment]
additional question: what happens if I have several charts in the same view ?

**Comment by jtblin** [comment]
Namespacing seems like a good idea, I'd prefer something like `chart-create` to be consistent with options. Probably not too much of a problem if you use a controller specifically for the chart but it could easily conflict.

If there are several charts, the event will be called several times accordingly. An improvement could be to pass an id so that it can be more easily matched.

**Comment by jtblin** [comment]
This is now done in the [chartjs-2.0 branch](https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0) which will be released when Chart.js 2.0 is released. Closing this issue.
