### ISSUE TITLE
Cannot add a dynamic loop array for label and data

### ISSUE THREAD

**Issue by Lightyearzz** [jtblin/angular-chart.js#261]
Hello,
I use the charts angular module and I meet a development problems about the creation of the curves of my chart. in fact, I try to create them dynamically from  table loop though the table fetches only the first value and the loop does not continue to create other points (see below)

![capture d ecran 2015-12-06 a 13 40 39](https://cloud.githubusercontent.com/assets/16175635/11613400/1e0d1aae-9c1f-11e5-83ac-df945abd4c30.png)

When I click on the button "OneMonth" The graph displays but displays only the first value. Here is an example of my code : 

![capture d ecran 2015-12-06 a 13 45 31](https://cloud.githubusercontent.com/assets/16175635/11613416/c59d5f22-9c1f-11e5-9083-445099101ca0.png)
![capture d ecran 2015-12-06 a 13 46 17](https://cloud.githubusercontent.com/assets/16175635/11613417/c59fb006-9c1f-11e5-9dc3-7fc15240d217.png)

Thank you in advance, I have tried several variant without reaching the desired result.

**Comment by jtblin** [comment]
It only displays one point because that's what your code do. `$scope.data = [[res.row.item(i).poids]]`. You are just overwriting the first element of the array, you'd want something like  `$scope.data[0].push(res.row.item(i).poids)`.

This is basic javascript and would be more appropriate for stackoverflow.com.
