### ISSUE TITLE
Dynamic chart not rendering properly

### ISSUE THREAD

**Issue by Zerokk** [jtblin/angular-chart.js#307]
I've got a code in which I show a canvas when I have some data inputted into a textfield. That's pretty straightforward.

After that, a doughnut chart appears with the data. This works perfectly. But as the chart appears, so it does a combobox where I can choose changing between a PolarArea chart, and the Doughnut chart. It works if I change them, but somehow, if I choose PolarArea and move my mouse over the chart, it sometimes changes to doughnut. When I move the mouse out, it sometimes returns to the Polar, sometimes not. 

Why does this happen? In some executions, this doesn't happen, which feels so strange.

**Comment by gkampjes** [comment]
This is a known issue, a fix is being worked on. See #187 for further information.

When changing certain data in the chart (e.g. labels, chart type) the directive destroys the chart and builds a new one, the problem is that sometimes it doesn't destroy the old chart, leaving both in the DOM.

I'm working on a fix currently.
