### ISSUE TITLE
Fixed Height Problem

### ISSUE THREAD

**Issue by flexdeviser** [jtblin/angular-chart.js#331]
chart options

responsive: true,
maintainAspectRatio: false

I want to make a "fiexed height" line-chart. As the document of Chart.js said, I just need to set a height(style="height:300px;") on the parent div. When I did it only use Chart.js, it worked, But it didn't work when I used your directive.

the reason is Chart.js calculates height using method "getMaximumHeight". 
in this line:
var container = domNode.parentNode;

domNode.parentNode is your "chart-container" div. so...............

**Comment by jtblin** [comment]
The parent div was needed originally because of a bug with Chart.js. After I submitted a fix, it wasn't needed anymore but I never go to actually remove the parent div. I don't know if anybody is relying on this now so I'm probably going to let it here for the `0.x` tree as I am pretty close to release `1.0.0` which is compatible with Chart.js `2.0`, see https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0 for more info. The `1.x` branch doesn't have the parent div anymore, therefore I'm going to close this as won't fix.
