### ISSUE TITLE
about data structure

### ISSUE THREAD

**Issue by anterokarttunen** [jtblin/angular-chart.js#353]
Hello,

Got a question. Is this kind of data structure supported http://www.chartjs.org/docs/#line-chart-data-structure ?

br, Antero

**Comment by jtblin** [comment]
No, there is a PR for that and we can reconsider at some point but it is not supported as of now.

**Comment by rafaellop** [comment]
@jtblin Could you please clarify how can I link data series with yaxes in the current angular-chart data structure? I've got troubles and you closed the issue (https://github.com/jtblin/angular-chart.js/issues/311#event-604295279) where I asked my question. The chart.js data structure allows to link series with yaxis, but I have no idea how to achieve the same in angular-chart.

**Comment by jtblin** [comment]
@rafaellop here is an example: https://github.com/jtblin/angular-chart.js/blob/chartjs-2.0/examples/app.js#L39. Note that you need the latest alpha version to use y-axis. Is that what you are looking for?

**Comment by rafaellop** [comment]
@jtblin thanks, I've seen the example before but it doesn't work for me. The second yaxis displays scale in the range -1 ... 1 completely ignoring the series and data. In fact I'm not quite aware how the scales definition in options is related to the data and series. Do you have any advice?

**Comment by rafaellop** [comment]
I have just updated again my `angular-chart.js` and `chart.js` libraries to the latest versions (1.0.0-alpha3 and 2.0-dev commited few hours ago) and I've got an error of:

`read property 'min' of undefined at update (chart.min.js:2570)`

which refers to code:

`if (yScale.min < 0 && yScale.max < 0) ` 
in the chart.js

So it seems that the chart.js just can't find the data for the defined multiple axes. My code is similar to the code in the example.js:

``<canvas id="line" class="chart" chart-line height="200" chart-data="intakeChartData"
chart-labels="intakeChartLabels" chart-series="intakeChartSeries"
chart-click="onIntakeChartClick" chart-options="intakeChartOptions" 
chart-colors="intakeChartColors" chart-y-axes="multiAxis">
</canvas>``

and the $scope have all these variables available on init, but I change them later from code depending on a user selected option.

With the latest `chart.js` it's obvious that the yaxes are not linked to any data because `chart.js` cannot find min/max values reporting undefined issue.

**Comment by rafaellop** [comment]
Sorry @jtblin my fault... Finally found the reason when logged datasets out just before the error. My `data` property contains 3 arrays of data while I defined two yaxes in the options. For me logical would be to define scales for the axes that I'd like to display and link them with the data somehow instead of remembering of using the same order in both arrays of data and scales. I fixed my issue by defining a third scale and set its display to false and everything started to work.

**Comment by frlinw** [comment]
Multi yAxes with bar/line chart would be useful ! +1

**Comment by jtblin** [comment]
@frlinw mutly y-axes are possible on: https://github.com/jtblin/angular-chart.js/tree/chartjs-2.0

**Comment by frlinw** [comment]
Yes, I can show 2 axes but how to link a dataset to the scale id ?

**Comment by jtblin** [comment]
https://github.com/jtblin/angular-chart.js/blob/chartjs-2.0/examples/app.js#L41

**Comment by frlinw** [comment]
I see the point. It works if there is one dataset for an axe... In my case, i have 2 datasets for an axes and one dataset for the other.... Is there a way to make it works ?

**Comment by jtblin** [comment]
It's supported since [alpha5](https://github.com/jtblin/angular-chart.js/releases/tag/1.0.0-alpha5). #336 tracks support for mixed types.
