### ISSUE TITLE
why does color default to `strokeColor` and not `fillColour` in `ChartJsFactory#getData`

### ISSUE THREAD

**Issue by shainegordon** [jtblin/angular-chart.js#362]
```
function getData (labels, data, colours) {
      return labels.map(function (label, i) {
        return angular.extend({}, colours[i], {
          label: label,
          value: data[i],
          color: colours[i].strokeColor,
          highlight: colours[i].pointHighlightStroke
        });
      });
    }
```

surely this should be `fillColor` and not `strokeColor`?

to me it does not really make sense that if I want to use an array color objects, instead of hex strings, that I need to declare as follows

`vm.chartColors.push({ strokeColor: '#fff' });`

this might not affect everyone, but in my case, I have a custom Pie chart, that allows different stroke/outline per slice, and as such, if I want a white slice with a black outline, I have to declare as follows: `vm.chartColors.push({ fillColor: '#000', strokeColor: '#fff' });` , which is backwards, and then in my custom chart's `addData` method I have to do `strokeColor : segment.fillColor,`. This is not a train smash, it just makes me feel a bit dirty inside

**Comment by jtblin** [comment]
This is because the colour generation / handling code is the same for line, bars and pie, doughnuts and I wanted to stick with the Chart.js theme of light colours for lines and bars, but if I don't invert the colours for pie and charts, I don't get the solid colours for pies and it looks weird.

Example:

Bar chart today:
![image](https://cloud.githubusercontent.com/assets/1388974/14575287/24ea2460-03a4-11e6-8ad8-efd4d3e902bd.png)

Pie chart today:
![image](https://cloud.githubusercontent.com/assets/1388974/14575320/598fc0f8-03a4-11e6-9365-43611fdf016a.png)

If I don't invert the colours for pie charts:
![image](https://cloud.githubusercontent.com/assets/1388974/14575331/6fbf45c4-03a4-11e6-8132-ba77f3db3ae4.png)

If I don;t use a light theme for bars:
![image](https://cloud.githubusercontent.com/assets/1388974/14575365/b91f90ca-03a4-11e6-8e6c-b7cf912f73b4.png)

So it's a question of look-n-feel for default colours, but yeah if you pass the colours yourself, it's a bit awkward from a semantic perspective. I could change that in the new version but I prefer the current look'n'feel for default colours.

**Comment by shainegordon** [comment]
ok, that makes perfect sense.

It is really not a huge deal from my side, I have added comments accordingly.

if a small bit of awkward looking code and a comment is the price to use this library, which makes life simpler, I will take it.
