### ISSUE TITLE
More control to Y-Axes

### ISSUE THREAD

**Issue by anttimann** [jtblin/angular-chart.js#365]
Can we add more control to Y-axes? 

#311 introduced multiple Y-axes but you cannot define which datasets is to be used in which Y-Axis.

Quick solution would be to change chartYAxes to an array that would match to datasets by index.

Here first and third dataset would go to Y-Axis 1 and second to Y-Axis 2
chart-data = [[1,2,3], [4,5,6], [7,8,9]]
chart-y-axes = ['y-axis-1', 'y-axis-2', 'y-axis-1']

It would be one line change:
from 
dataset.yAxisID = 'y-axis-' + (i + 1);

to
dataset.yAxisID = yaxis[i];

**Comment by anttimann** [comment]
or maybe better not break compatibility:

```
if (Array.isArray(yaxis)) {
   dataset.yAxisID = yaxis[i];
}  else {
   dataset.yAxisID = 'y-axis-' + (i + 1);
}
```

**Comment by jtblin** [comment]
Seems like a great idea! I don't think we care about compatibility for this as it was only introduced in `1.0-alpha` version and we are still in `alpha` mode so breaking changes are tolerated (API is unstable). I'd rather keep it simple. Would you mind sending a PR for that, otherwise I'll try and look at it soon?

**Comment by anttimann** [comment]
Sure. I'll do pull request for the change

**Comment by frlinw** [comment]
Thanks for that !
