### ISSUE TITLE
Angular Charts Not Working

### ISSUE THREAD

**Issue by Bassel-m** [jtblin/angular-chart.js#368]
I have an admin dashboard built with angularJS and angular material, everything was working okay and I left for like a month then when I opened it is not working saying 

**TypeError: (intermediate value)[e] is not a function**

You can see here: [www.basselahmed.com/myAdmin/ ](www.basselahmed.com/myAdmin/ )
**Please use --> username: tester --> password: tester**

I updated chartJS and Angular Chart JS and still nothing, Same Error.

**Comment by jtblin** [comment]
Looks like an issue with angular maybe. Anyway you'll have to debug and post and exact repro case. As you can see [here](http://jtblin.github.io/angular-chart.js/), everything works fine with the latest version.

**Comment by jtblin** [comment]
If you upgraded to the latest versions which uses 1.1.1 and that you use bower, it could be due to https://github.com/nnnick/Chart.js/issues/2230.

**Comment by bruc0** [comment]
Hi,
I enconuntered the same error. I simply copied the example to my app.

Error: (intermediate value)[e] is not a function

the log about this error is:

consoleLog/<()ionic.bundle.js:25642
$ExceptionHandlerProvider/this.$get</<()ionic.bundle.js:22421
$RootScopeProvider/this.$get</Scope.prototype.$digest()ionic.bundle.js:29013
$RootScopeProvider/this.$get</Scope.prototype.$apply()ionic.bundle.js:29263
timeout/timeoutId<()ionic.bundle.js:31030
completeOutstandingRequest()ionic.bundle.js:18706
Browser/self.defer/timeoutId<()ionic.bundle.js:18978
(Async: setTimeout handler) Browser/self.defer()ionic.bundle.js:18976
timeout()ionic.bundle.js:31019
C/<.link/<()angular-ui-router.min.js:7
createEventHandler/eventHandler()ionic.bundle.js:16583
triggerMouseEvent()ionic.bundle.js:2948
tapClick()ionic.bundle.js:2937
tapMouseUp()ionic.bundle.js:3013
(Async: EventListener.handleEvent) tapEventListener()ionic.bundle.js:2921
ionic.tap.register()ionic.bundle.js:2734
(Async: FrameRequestCallback) ionic.DomUtil.requestAnimationFrame()ionic.bundle.js:185
domReady()ionic.bundle.js:141
(Async: EventListener.handleEvent) <anonymous>ionic.bundle.js:147
<anonymous>ionic.bundle.js:133
<anonymous>

Is it possible that this is caoused by ui-router plugin? (maybe something wrong happens when DOM is requested in order to give height and width vars?)

BR,
bruc0
