### ISSUE TITLE
Normal line chart

### ISSUE THREAD

**Issue by vanzylv** [jtblin/angular-chart.js#456]
Hi,

I'm really having trouble drawing a normal line chart without a fill.It's easy enough to draw the standard one with bezier and fill but can't seem to get a normal one working.The biggest issue being able to remove the fill.See attached what I need.

Could somebody point me to an example.

Thanks

<img width="467" alt="screen shot 2016-08-04 at 09 51 51" src="https://cloud.githubusercontent.com/assets/9625074/17394399/23caef2a-5a29-11e6-89ff-3acfe1663a98.png">

**Comment by vysakhcv** [comment]
???

**Comment by vanzylv** [comment]
I'm not sure I understand,do you have a example?

**Comment by FurmanSK** [comment]
Same here, I couldn't figure out how to remove the fill from under the line. I've given up on this right now. Lot of the options shown aren't even configurable. I believe I got the color to change but that's it. Tension didn't work, nothing else worked for options. There needs to be more documentation on this wrapper for ChartJS

**Comment by bobbyfisher928** [comment]
So, I don't know if this helps, but here is an options object I created for a project I am working on. It created this graph: 

<img width="270" alt="screen shot 2016-08-04 at 10 12 08 pm" src="https://cloud.githubusercontent.com/assets/7718919/17424525/b16275ba-5a92-11e6-8257-037b072a44ac.png">

Inside my controller, I am using the same example line chart and date that is available on [angular-chartjs examples site](http://jtblin.github.io/angular-chart.js/). Direct your attention to the 'self.options.elements object. This is where you define the parameters for the graph types. In this case, you can change the fill, tension, and others that are defined on the [chartjs website](http://www.chartjs.org/docs/).

```
self.labels = ["January", "February", "March", "April", "May", "June", "July"];
  	self.series = ['Series A', 'Series B'];
  	self.data = [
    [65, 59, 80, 81, 56, 55, 40],
    [28, 48, 40, 19, 86, 27, 90]
  ];
  self.onClick = function (points, evt) {
    console.log(points, evt);
  };
  self.datasetOverride = [{ yAxisID: 'y-axis-1' }, { yAxisID: 'y-axis-2' }];
  self.options = {
  	maintainAspectRatio: false,
    scales: {
      	yAxes: [
        {
          	id: 'y-axis-1',
          	type: 'linear',
          	position: 'left',
	        ticks: {
		        display: false,
		        beginAtZero: true,
		        min: 0,
		        max:100,
		    },
		    gridLines: {
				tickMarkLength: 1,
				color: '#CFCFCF',
				zeroLineColor: '#CFCFCF'
		    }
        },
        {
          	id: 'y-axis-2',
          	type: 'linear',
          	position: 'right',
	        ticks: {
		        display: false,
		        beginAtZero: true,
		        min: 0,
		    },
		    gridLines: {
		    	tickMarkLength: 1,
		    	color: '#CFCFCF',
		    	zeroLineColor: '#CFCFCF'
		    }
        }
      	],
      	xAxes: [{
	        ticks: {
		        display: false,
		    },
		    gridLines: {
		    	tickMarkLength: 1,
		    	color: '#CFCFCF',
		    	zeroLineColor: '#CFCFCF'
		    }
      	}]
    },
    elements: {
    	line: {
    		fill: false,
    		tension: 0,
    		borderWidth: 5,
    	},
    	point: {
    		radius: 6,
    		borderWidth: 2,
    	},
    }
  };
```

The documentation is quite complex on [chartjs](http://www.chartjs.org/docs/) and does not provide a thorough example of the master options object with all attributes and properties completely defined. I am still learning, but I hope this helps. Feel free to ask any more questions.

Best regards,
Bobby

**Comment by vanzylv** [comment]
Thanks! Will give it a try

**Comment by FurmanSK** [comment]
Thanks Bobby! Trying right now. I've tried both angular-chart.js and also tc.chartjs and both don't work how I want based on lack of documentation. I love open source but it always lacks in documentation.

**Comment by bobbyfisher928** [comment]
Please let me know if this example helped you out vanzylv and FurmanSK.

**Comment by FurmanSK** [comment]
It did but now I have this issue. See how the red line is getting overlaid by the blue? And the date at the bottom, it has a gap at the end there if you can see. How do I fix these?

![image](https://cloud.githubusercontent.com/assets/5582608/17442078/0d1c81b0-5b02-11e6-884f-48fcb9e4aeea.png)

**Comment by FurmanSK** [comment]
Also, notice how the first point starts off the y-axis? Why is that? Is there a setting to force it to not do that or is that just how Chart.JS works?

**Comment by bobbyfisher928** [comment]
Are you using separate objects for the data and the options? If so, I am going to suggest you use the dataset object described in the ChartJs configuration.

```
data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
```
 I am actually converting all my code to use that format so I can't truly say whether it will work or not as of yet. 

Regarding your current dilemma, my suggestion is to switch the position of data going into the graph. I think it draws one data object, then goes back through if another data object is present, and overlays that on top. So, if you want the line to be on top, try switching the data objects position. 

For example, on [angualr-chart demo site](http://jtblin.github.io/angular-chart.js/), the data for the line is second after the bar data. Notice how the line goes behind the bar graph. Try switching the positions... 

<img width="1241" alt="screen shot 2016-08-05 at 11 57 31 am" src="https://cloud.githubusercontent.com/assets/7718919/17442539/36252b00-5b04-11e6-870b-53bb1b7c1ac0.png">

If that doesn't work, my next suggestion would be to use a more transparent 'rgba( )' value for the the blue line in your example above, and a less transparent 'rgba( )' for the red plot. 

To address the final spacing problem, I think you could set a scale step parameter. Because I cannot see the data you are working with, I can only assume that there may be more data points in the last section compared to the others...? I may be wrong with that assumption; however, that is what I am guessing. By the way, there is a date and time scale object you can work with and a whole slew of options and event triggers before the map build is begun where the step and scale parameters are built... I would give those a look. 

<img width="1110" alt="screen shot 2016-08-05 at 12 09 30 pm" src="https://cloud.githubusercontent.com/assets/7718919/17442784/873db650-5b05-11e6-8a3b-5bc269f0f8a4.png">

I am sorry I couldn't be more direct in my assistance, but I hope this helps. Keep me posted.

**Comment by FurmanSK** [comment]
Yeah I just saw that date/time parameter which looks nice. Thanks bobby, I'll give this a go and see what I can do. I thought maybe position was the issue too but the blue line is actually built first and stored first in the data array and then the average (red line) is stored after. Which is odd. I'll play with it some more.

Thanks!

**Comment by vanzylv** [comment]
@bobbyfisher928 

I would like to thank for the effort put into your replies.

BTW,works like a charm form me.

Thanks mate.

**Comment by bobbyfisher928** [comment]
I am glad I could help @vanzylv.

**Comment by jtblin** [comment]
Thanks @bobbyfisher928

**Comment by FurmanSK** [comment]
Yeah @bobbyfisher928  can't get the datasets to work. Here's my setup based on the example.  Gives me nothing for output. No graph starting to build or anything. The data inside datasets gets built in another function and set like this... 
"
        $scope.data.datasets[0].data = Data;
        $scope.data.datasets[1].data = runavg;
        $scope.data.labels = Labels;
"

    $scope.data = {
        labels: [],
        datasets: [
            {
                label: 'Recovery',
                data: [],
                backgroundColor: 'rgba(255, 99, 132, 0.2)',
                borderColor: 'rgba(255,99,132,1)',
                borderWidth: 1
            },
            {
                label: 'Run Avg',
                data: [],
                backgroundColor: 'rgba(203, 0, 0,1)',
                borderColor: 'rgba(203, 0, 0, 0.8)',
                borderWidth: 1                  
        }]
    }
    
    
    $scope.options = {
        maintainAspectRatio: false,
        scales: {
            yAxes: [
                {
                    id: 'y-axis-1',
                    type: 'linear',
                    position: 'left',
                    ticks: {
                        display: true,
                        beginAtZero: true,
                        min: 90,
                        max: 100,
                    }
                }
            ],
            xAxes: [
                
            ]
        },
        elements: {
            line: {
                fill: false,
                tension: 0.4,
                borderWidth: 2,
            },
            point: {
                radius: 0,
                borderWidth: 0,
                hitRadius: 2
            },
            title: {
                display: true,
                text: 'Recovery Chart'
            }
        },
        animation: {
            //easing: 'easeInQuad',
            duration: 1000
        }
    };

**Comment by bobbyfisher928** [comment]
Hey @FurmanSK. I have since learned that the suggestion I gave is not compatible with angular-chart mixin. Use the datasetOverride to overwrite the options for each line of the graph. In the example below, I have three lines on the graph as represented by my self.data object containing three arrays. Each one needed to be a different color. The output looks like this:

<img width="256" alt="screen shot 2016-08-16 at 11 09 20 am" src="https://cloud.githubusercontent.com/assets/7718919/17704108/f82dffb0-63a1-11e6-9b3b-7aa0b7ca59e9.png">


Here is an example of how I was able to modify this graph using the objects provided within [Chart.js documentation for line graph](http://www.chartjs.org/docs/#line-chart-introduction):

```
self.labels = ["1","2","3","4","5"];
self.series = ['Series A','Series B'];

self.data = [
	[self.r(),self.r(),self.r(),self.r(),self.r()],
	[self.r(),self.r(),self.r(),self.r(),self.r()],
	[self.r(),self.r(),self.r(),self.r(),self.r()]
];

	self.datasetOverride = [
        {
            label: "Title",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "#F9ED37",
            borderColor: "#F9ED37",
            borderDash: [],
            pointBorderColor: "#F9ED37",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 3,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "#F9ED37",
            pointHoverBorderColor: "#F9ED37",
            pointHoverBorderWidth: 3,
            pointRadius: 6,
            pointHitRadius: 10,
            spanGaps: false,
        },
        {
        	label: "title2",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "#8CC63E",
            borderColor: "#8CC63E",
            borderDash: [],
            pointBorderColor: "#8CC63E",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 3,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "#8CC63E",
            pointHoverBorderColor: "#8CC63E",
            pointHoverBorderWidth: 3,
            pointRadius: 6,
            pointHitRadius: 10,
            spanGaps: false,
        },
        {
        	label: "title3",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "#46BFF3",
            borderColor: "#46BFF3",
            borderDash: [],
            pointBorderColor: "#46BFF3",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 3,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "#46BFF3",
            pointHoverBorderColor: "#46BFF3",
            pointHoverBorderWidth: 3,
            pointRadius: 6,
            pointHitRadius: 10,
            spanGaps: false,
        }

    ]

	self.options = {
		maintainAspectRatio: false,
	    scales: {
	      yAxes: [{
	      	position: 'right',
	      	ticks: {
	      		display: false,
	      		mirror: false,
	      		fontSize: 8,
	      		padding: 15,
	      		beginAtZero:true,
	      		max: 60,
	      	},
	      	gridLines: {
	      		display: false,
	      		drawBorder: false,
	      	},
	      }
	      ],
	      xAxes: [{
	      	display: false,
	      	ticks: {
	      		display: true,
	      		mirror: true,
	      		fontSize: 8,
	      		padding: 5,
	      		beginAtZero:true
	      	},
	      	gridLines: {
	      		display: true,
	      		drawBorder: false,
	      	}
	      }
	      ]
	    },
	    elements: {
	    	line: {
	    		tension: 0,
	    		borderWidth: 4,
	    		fill: false,
	    	},
	    	point: {
	    		backgroundColor: '#fff',
	    		borderWidth: 3,
	    		radius: 6
	    	}
	    }
  	};
```

ChartJS declares this dataset object for a line chart which can be inserted into the datasetOveride object and works perfectly on my system. Data will not be managed by the datasetOveride. Everything else works. Create a datasetOveride array of objects for each line. You can even go further and create a function that builds this object based on the length of the data array. 

***(Only Pay attention to the dataset object and see how I utilized it in my example above.)***
```
var data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            label: "My First dataset",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "rgba(75,192,192,0.4)",
            borderColor: "rgba(75,192,192,1)",
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: "rgba(75,192,192,1)",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(75,192,192,1)",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            spanGaps: false,
        }
    ]
};
```

Let me know if this helps.

best regards,
Bobby Fisher

**Comment by FurmanSK** [comment]
Yes that helped. I have another question but I'll either PM you or make another post. Thanks for the help!

-Wes
