### ISSUE TITLE
Putting value inside doughnut

### ISSUE THREAD

**Issue by Tatenda** [jtblin/angular-chart.js#478]
Hello. I am using this directive and it works perfectly. However i was wondering how do i put a value inside the empty circle of a doughnut chat. Are there axamples you can point me to that can show me how to solve this using this directive.

**Comment by Olmer1st** [comment]
+1

**Comment by WilliamJohnsonJr** [comment]
I haven't discovered a way to do this by using the directive, but I have done this with HTML and CSS by placing the canvas tag for the chart inside a container (let's call it chartContainer), absolutely positioning another container of the same width and height as the chart canvas on top of the chart (let's call it infoContainer), and then flexboxing the contents inside of the infoContainer so that they are centered over the hole. Here's an example:

HTML:
`<div class="chartContainer">
     <canvas id="infoChart" class="chart-doughnut" chart-data="chartData" chart-labels="chartLabels">
     </canvas>
     <div class="infoContainer">
         <p class="holeText">
             Doughnut-Hole Text
         </p>
      </div>
 </div>`

CSS:
.chartContainer{
        /* Flex positioning here ensures that the doughnut chart is centered in the container */
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
          /* Relative positioning allows us to absolutely position the holeText in .infoContainer below */
	position: relative;
        width: 306px;
	height: 168px;
}

.infoContainer{
	position: absolute;
	top: 4px;
	left: 0;
	width: 306px;
	height: 153px;
        /* Flex positioning ensures that the enclosed p tag is centered horizontally and vertically in the container*/
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
}

.holeText{
   text-align: center;
}

Note: you could also absolutely position the chart canvas (rather than the holeText) so that it sits on top of the text you want to appear inside the doughnut. This should still allow you to hover over the doughnut to see various labels and values highlighted.

If anyone has figured out how to do this without using some HTML/CSS wizardry, I'm all ears.

**Comment by jtblin** [comment]
I don't think Chart.js supports this: http://www.chartjs.org/docs/#doughnut-pie-chart

**Comment by doodirock** [comment]
It looks like its doable with a plugin.  

http://stackoverflow.com/questions/20966817/how-to-add-text-inside-the-doughnut-chart-using-chart-js

Is there anyway to Chart.types.Doughnut.extend from within angular?

https://jsfiddle.net/cmyker/ooxdL2vj/

**Comment by MohamedSahir** [comment]
How can i do it same for angular4 components?

**Comment by ihareal** [comment]
How can i apply this plugin not for all charts but on current?
