### ISSUE TITLE
Changing the point style to line makes the point go blank

### ISSUE THREAD

**Issue by jpmnteiro** [jtblin/angular-chart.js#509]
Hey,

First off, thank you for the library, it's great.

I've been playing around with it, particularly with the points. I've tried changing the points style to `line` but for some reason they appear as blank. They are in the chart (i.e, if you hover them, you can see the tooltip and it shows the point) but it's as if they are not coloured.

Any thoughts?

Here's an example: http://jsbin.com/mujemipepe/edit?html,js,output

**Comment by jtblin** [comment]
Hey, no I'm sorry but I don't see what the issue is, your configuration for the options seem to be correct so you should probably open an issue on the Chart.js tracker.

Unrelated but the attribute for series should be `chart-series` not just `series` and the `legend` attribute does not exist in 1.x anymore (replaced by native chart.js option).
