### ISSUE TITLE
How can I change the background color to the chartArea?

### ISSUE THREAD

**Issue by echavezNS** [jtblin/angular-chart.js#529]
Hi, I've been trying to change the background color without using CSS because it change the background color to the whole square (chart/labels), is there any way to change the background color to just the area I need? (see the image below).

![image](https://cloud.githubusercontent.com/assets/17257421/19414978/2b37d64c-931d-11e6-9be2-207d8a6726d5.png)

Hopefully someone can help me with this.

**Comment by mathben** [comment]
The answer is suppose to be here, but I cannot find it (because maybe the feature not exist)
http://www.chartjs.org/docs/#chart-configuration-chart-data

I am sure you need to ask chart.js and not angular-chart.js
https://github.com/chartjs/Chart.js/issues

I think you need to draw it manually if you only need to draw the area you want, like this answer : 
https://github.com/chartjs/Chart.js/issues/3416

**Comment by echavezNS** [comment]
@mathben Thanks, I will move this question to the Chart.js repo.

**Comment by craigcosmo** [comment]
can you give the link to your question on chartjs repo ?

**Comment by mathben** [comment]
The same question in https://github.com/chartjs/Chart.js/issues
https://github.com/chartjs/Chart.js/issues/3479
