### ISSUE TITLE
Reference to created chart object

### ISSUE THREAD

**Issue by csheets** [jtblin/angular-chart.js#53]
Wondering if it possible to get a reference to the created ChartJS chart object created by the directive from inside a controller? I basically need to further customize the chart and or call some of the chart methods. Is there any sort of event that can be tied into that occurs after the chart is created? Any help or ideas would be greatly appreciated - thanks!

**Comment by jtblin** [comment]
Thanks for the great suggestion. This is now implemented and published in `0.4.0`. You can now listen to the `create` and `update` events on the scope and retrieve the chart as the argument:

```
$scope.$on('create', function (chart) {
  console.log(chart);
});
```

**Note that the event can be emitted multiple times for each chart as the chart can be destroyed and
created multiple times due to angular `watch` lifecycle.**

**Comment by newtonwagner** [comment]
Just to add a little update note, the listener function get the event object as the first param, so the solution is:

```
$scope.$on('create', function (event, chart) {
  console.log(chart);
});
```

**Comment by jeetu3indra** [comment]
Thanks a lot @newtonwagner. Suggestion saved me a lot of time!

**Comment by esteban-filardi** [comment]
Just wanted to add that as version 1.0.0 of angular-chart.js (It uses Chart.js 2) the code required to make this is

    $scope.$on('chart-create', function (event, chart) {
        console.log(chart);
    });
