### ISSUE TITLE
chart-colors not working

### ISSUE THREAD

**Issue by mattbajorek** [jtblin/angular-chart.js#532]
When adding the attribute chart-colors to the canvas for a bar graph: 
```
chart-colors= [{
    fillColor: 'rgb(54,172,207)',
    strokeColor: 'rgb(54,172,207)',
    highlightFill: 'rgb(54,172,207)',
    highlightStroke: 'rgb(54,172,207)'
}]
```
The bar colors instantly go to a grey -> rgba(0,0,0,0.1) as the global default noted in: http://www.chartjs.org/docs/#chart-configuration-colors.

It doesn't matter what inputs are in the array, but the fact that there is an array makes it go to grey.  I know it is registering because the grey bar is different than the default bar color.  By using:

```
.config(['ChartJsProvider', function (ChartJsProvider) {
    // Configure all charts 
    ChartJsProvider.setOptions({
      chartColors: ['#36accf']
    });
  }])
```

I am able to change the chart color, but not all the specific details that I want to change.  Any help is appreciated.  Thanks!

**Comment by SirBryan** [comment]
This is because the names have changed. "fillColor", "strokeColor", etc. no longer work.

I looked at the Chart.js documentation (see [http://www.chartjs.org/docs/#chart-configuration-colors]) and the angular-chart.js code, and found the following:

```
        backgroundColor: rgba(color, 0.2),
        pointBackgroundColor: rgba(color, 1),
        pointHoverBackgroundColor: rgba(color, 0.8),
        borderColor: rgba(color, 1),
        pointBorderColor: '#fff',
        pointHoverBorderColor: rgba(color, 1)
```

So this means the documentation needs to be updated to match.  In your case, 
```
fillColor = backgroundColor
strokeColor = borderColor
```

I don't know what the highlight colors would be (probably the pointHover colors).

**Comment by mattbajorek** [comment]
Thanks! I got rid of highlightFill and highlightStroke.  Then changed fillColor and strokeColor like you suggested and its working the exact way I wanted.  I appreciate the time you took to answer this very detailed and correct answer.
