### ISSUE TITLE
Grunt and folder  with dots

### ISSUE THREAD

**Issue by tpoxa** [jtblin/angular-chart.js#80]
Running "rev:dist" (rev) task
dist/public/app/app.js >> c389c03b.app.js
dist/public/app/vendor.js >> ea6834d9.vendor.js
Warning: Unable to read "dist/public/bower_components/Chart.js" file (Error code: EISDIR). Use --force to continue.

grunt --version
grunt-cli v0.1.13
grunt v0.4.5

**Comment by jtblin** [comment]
Open a bug on grunt.

**Comment by mariostesla** [comment]
you can exclude it like this  '!**/Chart.js/**'

**Comment by vthinkxie** [comment]
+1

**Comment by AleksMeshkov** [comment]
@mariostesla 
I've added this into the exclude array. Now I'v got an error.

```Running "wiredep:target" (wiredep) task
Warning: Invalid regular expression: /!**/Chart.js/**/: Nothing to repeat Use --force to continue.```

**Comment by mariostesla** [comment]
@AleksMeshkov i'm not using any tasks that have this problem now, but wiredep has an `exclude` option so you can use it for this issue

i guess something like this will do
```
'wiredep': {
      app: {
        src: '<%= yeoman.app %>/index.html',
        ignorePath: '<%= yeoman.app %>/',
        exclude: ['bower_components/Charts.js']
      }
    },
```

**Comment by vineshhpatel** [comment]
@AleksMeshkov You saved time !!!

**Comment by jpstone** [comment]
Does this have anything to do with '.js' being in the folder name?

**Comment by vineshhpatel** [comment]
@jpstone Yup. for example `Chart.js/dist/chart.js`

**Comment by SaintPeter** [comment]
Thanks @mariostesla - This fixed my problem and saved me time!

**Comment by diegofernandes** [comment]
I used `<%= yeoman.dist %>/public/{,*/,Chart.js/}*.{js}`

**Comment by azachar** [comment]
I found it really very weird that you do not follow any conventions for the name! You did a great job and provided really cool library but why you are forcing lot of people need to tweak their environment in order to make it run. Why is you do not call the library _angular-chart-js_ and we are all done here. I guess this should not be closing without ignoring it.

**Comment by jtblin** [comment]
@azachar the bug is about the dot in _Chart.js_. I didn't create _Chart.js_, _angular-chart.js_ is merely a wrapper around it, so I am not ignoring the comments, there is just nothing I can do about it. Now you could say the same for _angular-chart.js_ but it wouldn't solve the problem with _Chart.js_ and it is a bit late for renaming it tbh.

**Comment by azachar** [comment]
@jtblin  Sorry for the comment, it belongs to an another repo... Chart.js, heh

**Comment by jpstone** [comment]
I think this is more a limitation with bower. If there is an npm package, we could just use that.

**Comment by gkampjes** [comment]
There is an npm package: https://www.npmjs.com/package/angular-chart.js
