### ISSUE TITLE
Chart.js + Angular-Chart doesn't work in IE8

### ISSUE THREAD

**Issue by jonathancohen4221** [jtblin/angular-chart.js#89]
Hi,
I have an issue with this great angular-chart plugin. It doesn't work in IE8 even if i add excanvas and es5-shim. The Charts are not displayed. I add excanvas and es5-shim but i have an error "TypeError: 'document.defaultView' is null or not an object. Have you expected the same issue ? Does anyone have a solution ? I've been searching for a solution for 2 days but i don't succeed :(

Thank you very much for your help

**Comment by romain-ni** [comment]
Hi Jonathan,
I fought a lot to get it to work on IE8 too and finally succeeded. I used to have a lot of "Object doesn't support this property or method"
I never had "TypeError: 'document.defaultView' is null or not an object" issue though.

I used this if statement a lot to make IE8 exception :
```
if (typeof window.G_vmlCanvasManager === 'object' && window.G_vmlCanvasManager !== null) {
          // Remove animation for IE8
          scope.options.animation = false;
}
```

I updated getColor function in angular-chart.js because IE8 doesn't support rgba :
```
function getColour (colour) {
    // IE8 won't support rgba()
    if (typeof window.G_vmlCanvasManager === 'object' && window.G_vmlCanvasManager !== null) {
      return {
        fillColor: rgb(colour),
        strokeColor: rgb(colour),
        pointColor: rgb(colour),
        pointStrokeColor: '#fff',
        pointHighlightFill: '#fff',
        pointHighlightStroke: rgb(colour)
      };
    } else {
      return {
        fillColor: rgba(colour, 0.2),
        strokeColor: rgba(colour, 1),
        pointColor: rgba(colour, 1),
        pointStrokeColor: '#fff',
        pointHighlightFill: '#fff',
        pointHighlightStroke: rgba(colour, 0.8)
      };
    }
  }
```
I update setLegend function (changed the div to an aside element) that was rendering the legend in the div of the chart instead of the div of the legend : 
```
function setLegend (elem, chart) {
    var $parent = elem.parent(),
        $oldLegend = $parent.find('aside'),
        legend = '<aside id="legend" class="chart-legend">' + chart.generateLegend() + '</aside>';

    if ($oldLegend.length) {
      $oldLegend.replaceWith(legend);
    }
    else {
      $parent.append(legend);
    }
  }
```

My advice would be just go step by step, using console.log or alert messages to identify where IE8 breaks and fix it.
Good luck.

**Comment by jtblin** [comment]
Thanks a ton for the detailed tutorial @romain-ni :+1:

**Comment by jtblin** [comment]
For `rgba` issue, now that I think about it, I could add a simple polyfill e.g.

    if (typeof `rgba` === 'undefined`) var rgba = rgb

That should work. If the legend trick has no impact on other browsers, I don't mind integrating this. PR welcome :)

**Comment by jtblin** [comment]
Thanks to @travellingprog, IE8 support should not be an issue anymore.

**Comment by tomvonclef** [comment]
The issue is that there's a line in Chart.js that is not compatible with IE8 without polyfills. But the line is not called (I think) unless you fail to use the ```height``` and/or ```width``` attributes on ```<canvas>```. So the simple fix is to use ```height``` and ```width``` in the HTML.

At least that was causing the ```document.defaultView``` is ```null``` error for me in IE8. Below is a more detailed explanation, which probably is not needed as long as ```height``` and ```width``` are used:

---

This is a Chart.js issue, really. I'm using Chart.js v1.0.2, and it includes the line:

```javascript
return document.defaultView.getComputedStyle(element).getPropertyValue(dimension);
```

IE8 does not support ```document.defaultView```, which is just an alias for ```window```. IE8 also does not support ```getComputedStyle()```. I was already using html5shiv, es5-shim, and modernizr, but they don't provide help with either of these IE8 missing features.

I added ```document.defaultView``` and ```getComputedStyle()``` to IE8 using "polyfill.js" at <https://github.com/Financial-Times/polyfill-service/tree/master/polyfills/getComputedStyle> and a one-liner:

```javascript
<!--[if lt IE 9]>
    <script src="/scripts/ie8-polyfill-getComputedStyle.js"></script>
    <script>
        document.defaultView = window;
    </script>
<![endif]-->
```

**Comment by jtblin** [comment]
Thanks for the info @tomvonclef. I've added that to the readme.

**Comment by tomvonclef** [comment]
I should also clarify that while adding the ```getComputedStyle()``` polyfill and setting ```document.defaultView = window``` fixed the IE8 issue that @jonathancohen4221 had, there were further issues that arose from not having ```height``` and ```width``` set on ```<canvas>```. I didn't end up debugging these, because I figured out that I could fix the issues by having ```height``` and ```width``` attributes. I'm going to do a pull request on the README for this.

**Comment by tomvonclef** [comment]
Here is the pull request: https://github.com/jtblin/angular-chart.js/pull/195.

I removed the ```getComputedStyle()``` and ```document.defaultView``` polyfills from the example code for IE8 and below because they should not be needed unless ```height``` and ```width``` are not set on ```<canvas>```.
